# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/focal64"
  config.vm.synced_folder "code", "/compiler_code"
  config.vm.provider "virtualbox" do |vb|
     vb.gui = false
     vb.memory = "1024"
     vb.name = "compilers"
     vb.cpus = 2
     vb.customize ["modifyvm", :id, "--cpuexecutioncap", "80"]
   end

   config.vm.provision "shell", inline: <<-SHELL
     apt-get update
     apt-get install -y build-essential
     apt-get install -y openjdk-8-jdk openjdk-8-doc openjdk-8-jre-lib
     apt-get install -y ant
   SHELL
end
